server:
  port: 9902
spring:
  application:
    name: service2
  config:
    import: vault://

  datasource:
    url: jdbc:postgresql://${SPRING_POSTGRES_HOST:localhost}:${SPRING_POSTGRES_PORT:5432}/${SPRING_POSTGRES_DB:mydb}
    username: ${SPRING_POSTGRES_USER:myuser}
    password: ${SPRING_POSTGRES_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    vault:
      uri: https://127.0.0.1:8200
      scheme: https
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: secret
        backend-version: 2
        default-context: service2
        application-name-context: false
        profile-separator: ','
      ssl:
        trust-store: file:/tmp/vault-truststore.p12
        trust-store-password: changeit
        trust-store-type: PKCS12
